### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Chevit** [medallia/Digital-iOS-SDK#4]
Please don't do fixes in this way.

If you want to fix anything - add a new tag.
At this moment our builds are broken cuz Xcode 13.2 can't find package product 'MedalliaPackage'. And 
And the previous version was good.
'Reset packages cache' and other commands don't help. As result, we will try to use manual integration and this is not the first time.

<img width="355" alt="Screenshot 2022-03-21 at 14 06 07" src="https://user-images.githubusercontent.com/750928/159257741-8e483095-fd69-4962-b59f-86e6baaaa6be.png">
<img width="880" alt="Screenshot 2022-03-21 at 14 07 15" src="https://user-images.githubusercontent.com/750928/159257933-03772762-48dc-4aeb-9d88-afd896a9d015.png">
<img width="589" alt="Screenshot 2022-03-21 at 14 07 51" src="https://user-images.githubusercontent.com/750928/159257940-f73ffb77-f2eb-41c5-949c-9fa9e5658214.png">

**Comment by OriMedallia** [comment]
Hi @Chevit 
What you're suggesting won't work in Xcode 13.3 and above.

First, you need to remove the package from your project
Clear the Swift Package Manager cache on your machine by going to ~/Library/Caches/org.swift.swiftpm/ and delete:
Digital-iOS-SDK folder
Digital-iOS-SDK lock file
Then please reintegrate with version 4.0.2

If for some reason it doesn't work for you please contact your Medallia's CSM and we'll schedule a meeting.

**Comment by noelstieglitz** [comment]
We ran into the same issue.  Our build broke and I can't re-add it using SPM for a specific version or range of versions (like we were doing).  

I'm working around this issue by pointing to the main branch rather than specifying a version.

**Comment by OriMedallia** [comment]
Hi @noelstieglitz 
You can point to exact version 4.0.2 or if you don't want to use exact version it should be between 4.0.0 to 5.0.0
You can see that the 4.0.2 tag exist here https://github.com/medallia/Digital-iOS-SDK/tags
If you're still experiencing this issue, please contact your Medallia's CSM and we'll schedule a meeting

**Comment by noelstieglitz** [comment]
@OriMedallia thanks for following up.  We were successfully referencing this project pointing to `3.9.1` prior to the update to this repo ~8 days ago. After the latest changes, I receive an error on my dev machine (as well as in the CI pipeline, pointing to it *not* being a cache issue) trying to reference this library using SPM.  As I mentioned in my previous comment, I also am not able to add a reference using a specific version or a range of versions.  Steps to reproduce:

1. Clear the cache per your recommendation above.
2. Following the steps described in the readme (https://github.com/medallia/Digital-iOS-SDK/blob/main/README.md), reference a specific version or range of versions.  Try `4.0.2` or `4.00` - `5.0.0`.
3. See an error in the Xcode SPM UI that the "package resolution failed"

I can temporarily work around this issue by following the steps in the readme, except instead of choosing a specific version or a range of versions, choosing "branch" -> main.  This is obviously a bad long term solution because anytime you push to this repo, we'll get latest, which could cause unexpected changes in our CI pipeline vs. our local environment. @Chevit's solution is the better long term solution if you guys aren't able to fix the repo.

Interestingly I'm not seeing any reference to the previously existing (at least looking at our references, looks like it used to exist) `3.9.1` tag and I'm seeing multiple commits against the same `4.0.2` tag.

**Comment by OriMedallia** [comment]
@noelstieglitz  Can please try to create a new project with v4.0.2 and let me know if the issue is reproduceable on an empty project? Thanks
